project:
  type: website

website:
  title: "crypto trends"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: sources.qmd
        text: Sources
      - href: trends.qmd
        text: Trends
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



